CREATE TABLE `products` (
  `id` int NOT NULL AUTO_INCREMENT,
  `productCode` varchar(45) NOT NULL,
  `name` longtext NOT NULL,
  `description` longtext,
  `price` int NOT NULL,
  `qty` int DEFAULT '0',
  `category_id` int NOT NULL,
  `active` tinyint NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `webItem` tinyint NOT NULL DEFAULT '1',
  `preOrderStart` timestamp NULL DEFAULT NULL,
  `preOrderEnd` timestamp NULL DEFAULT NULL,
  `summary` text,
  `brandId` int DEFAULT NULL,
  `productTypeId` int DEFAULT NULL,
  `releaseDate` timestamp NULL DEFAULT NULL,
  `arrivalDate` timestamp NULL DEFAULT NULL,
  `manufacturerId` int DEFAULT NULL,
  `recomended` tinyint DEFAULT '0',
  `poPrice` int DEFAULT '0',
  `spPrice` int DEFAULT NULL,
  `poDeposite` int DEFAULT NULL,
  `spStartDate` varchar(45) DEFAULT NULL,
  `spEndDate` timestamp NULL DEFAULT NULL,
  `weight` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
